# Generated by Django 5.2.5 on 2025-09-08 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_task_options_task_status_task_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='type',
            new_name='type_old',
        ),
    ]
