# Generated by Django 5.2.5 on 2025-09-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_type_task_type_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='task_set', to='webapp.type', verbose_name='Тип(ы)'),
        ),
    ]
