# Generated by Django 5.2.5 on 2025-09-08 18:22

from django.db import migrations

def transfer_types(apps, schema_editor):
    Task = apps.get_model('webapp.Task')
    for task in Task.objects.all():
        task.types.add(task.type_old)


def rollback_transfer(apps, schema_editor):
    Task = apps.get_model('webapp.Task')
    for task in Task.objects.all():
        task.type_old = task.types.first() if task.types.exists() else None


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_task_types'),
    ]



    operations = [
        migrations.RunPython(transfer_types, rollback_transfer)
    ]
