# Generated by Django 5.2.5 on 2025-09-16 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20250908_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='type_old',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='webapp.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='task',
            name='types',
            field=models.ManyToManyField(related_name='task_set', to='webapp.type', verbose_name='Тип(ы)'),
        ),
    ]
