# Generated by Django 5.2.5 on 2025-10-02 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_project_author_task_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='projects_part', to=settings.AUTH_USER_MODEL, verbose_name='Участник(и)'),
        ),
    ]
