# Generated by Django 5.2.5 on 2025-10-02 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_project_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('add_participants', 'Can add participants'), ('delete_participants', 'Can delete participants')], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
    ]
