# Generated by Django 5.2.5 on 2025-11-02 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_task_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='author',
        ),
        migrations.RemoveField(
            model_name='task',
            name='author',
        ),
    ]
